### ISSUE TITLE
500 internal error on validation API reported

### ISSUE THREAD

**Issue by siemvaessen** [IATI/IATI-Validator-Actual#19]
**The bug**
500 internal URI issue

**Reproduce**
1. Go to 'https://www.afdb.org/sites/default/files/iati/iaticapeverdedata.xml'
2. md5 value generated '4b4e9743feffbdee827723fd75d6101b'
3. See validator result @ 'https://iativalidator.iatistandard.org/api/v1/iati-files/file/json/4b4e9743feffbdee827723fd75d6101b.json'
4. See 500 internal error

**Expected behavior**
Would expect an actual result at @ 'https://iativalidator.iatistandard.org/api/v1/iati-files/file/json/4b4e9743feffbdee827723fd75d6101b.json' and not the 500 internal error

**Additional context**
Tied into an issue reported on iati.cloud end [here](https://github.com/zimmerman-team/iati.cloud/issues/2543).

**Comment by siemvaessen** [comment]
How are MD5 codes for files generated within the IATI Validator btw?

**Comment by amy-silcock** [comment]
Hi @siemvaessen, the MD5 codes are created using the full xml as downloaded from the DS (per file).

The Validator should be returning a 404 error, rather than a 500 when the MD5 code doesn't exist. We'll work this into the next release of the Validator.

**Comment by siemvaessen** [comment]
Regardless of error-type it seems data that is available from a publisher (afdb) and it looks from the [Validator perspective ](https://iativalidator.iatistandard.org/view/dqf/files/601aa9356a7b2b0018a2e789)no critical issue is reported - however, Datastore does not look at a webpage for Validator messaging, it only looks at the Validator API for a request with the md5 key.

The Validator API request provides an error (currently 500). 

Could someone point us to the correct Validator API response for this specific afdb (Cabo Verde file) and find out why the  [Validator perspective ](https://iativalidator.iatistandard.org/view/dqf/files/601aa9356a7b2b0018a2e789) fro this file looks ok and the Validator API request provides an error?

**Comment by alexlydiate** [comment]
The Validator has not changed the way it generates its MD5 since the initial release - the code for that operation is here:

https://github.com/IATI/IATI-Validator-Server/blob/master/server/boot/jobs/datastore.js#L31

Using the standard Node library MD5 function, hashing the XML as downloaded from the Datastore.

This is how it produces its MD5 hash for _every_ file, and it does so once, on that line.

So, if the Datastore is managing to retrieve _some_ files using the MD5 it generates but not others, that indicates the underlying issue - beyond the relatively trivial issue of the return of HTTP status code 500 instead of 404 when a file is not found - would lie with the Datastore, and with it producing inconsistent hashes.

For reference, the JSON report for the specific file is here: https://iativalidator.iatistandard.org/api/v1/iati-files/file/json/3c31ca011a5e50c9ca508cf1cf893dfa.json

And related page on the Validator Web site is here: https://iativalidator.iatistandard.org/view/dqf/files/601aa9356a7b2b0018a2e789

There are two possibilities here - either this issue has been extant since launch six months ago - and if so, it is a concern that the Datastore has no error reporting in place to notice it earlier - or that a recent change in the Datastore has introduced the problem.

As it stands, the design of this integration is inherently fragile - there is no reason to rely on both systems producing the hash. That is something we will rectify with V2 of the validator, and in the public API it releases - that intends to return validation reports identified by common identifiers as obtained from the Registry.

**Comment by andylolz** [comment]
I get the same hash as Siem using `md5sum`, or in python:

```python
import requests
from hashlib import md5

r = requests.get('https://www.afdb.org/sites/default/files/iati/iaticapeverdedata.xml')
print(md5(r.content).hexdigest())  # 4b4e9743feffbdee827723fd75d6101b
```

The validator appears to be using a different hash: [3c31ca011a5e50c9ca508cf1cf893dfa](https://iativalidator.iatistandard.org/api/v1/iati-files/file/json/3c31ca011a5e50c9ca508cf1cf893dfa.json).

My guess it’s referring to an older version of the file. I don’t know how as a user I would confirm that, though – I don’t see a timestamp, or a link to the source XML on the validator frontend.

**Comment by alexlydiate** [comment]
Thanks @andylolz  - that is an excellent insight.

There is no manner of accessing the Validator source xml publically, but we do keep it in store, for precisely this reason :)

The two files do indeed differ - the opening Activities tages are

<iati-activities version="2.01" generated-datetime="2020-12-22T17:26:05">

and

<iati-activities version="2.01" generated-datetime="2021-01-28T14:00:06">

Respectively.

So, from there you would assume that the Datastore is generating the MD5 from the current version, but reporting the old version to the Validator.

**Comment by alexlydiate** [comment]
And indeed, whist the Datastore holds the new version on file, its API is still reporting the same SHA1 hash as the old version. It's response (as of 12:00 on 26th Feb) is here:

`{
	"url": "http://iati.cloud/api/datasets/1298/?format=json",
	"name": "afdb-capeverde",
	"title": "Cape Verde",
	"filetype": "Activity",
	"publisher": {
		"url": "http://iati.cloud/api/publishers/64/?format=json",
		"publisher_iati_id": "46002",
		"display_name": "African Development Bank",
		"name": "afdb"
	},
	"source_url": "https://www.afdb.org/sites/default/files/iati/iaticapeverdedata.xml",
	"activities": "http://iati.cloud/api/activities/?dataset=1298&format=json",
	"activity_count": 66,
	"date_created": "2013-06-28T16:43:52.259852",
	"date_updated": "2021-01-28T23:04:48.858828",
	"last_found_in_registry": "2021-02-20T20:25:49.517182",
	"iati_version": "2.01",
	"sha1": "cf6101f1c9f8b882a9875076ec05854781910453",
	"note_count": 327,
	"added_manually": false,
	"internal_url": "https://iati.cloud/static/datasets/46002/Activity/2.01/iaticapeverdedata.xml"
}`

And the Validator DB record for the same is:

`{
        "_id" : ObjectId("601aa9356a7b2b0018a2e789"),
        "internal_url" : "https://iati.cloud/static/datasets/46002/Activity/2.01/iaticapeverdedata.xml",
        "sha1" : "cf6101f1c9f8b882a9875076ec05854781910453",
        "__v" : 0,
        "created" : ISODate("2013-06-28T16:43:52.259Z"),
        "downloaded" : ISODate("2021-01-28T23:04:48.858Z"),
        "filename" : "iaticapeverdedata.xml",
        "lastseen" : ISODate("2021-02-16T08:59:38.671Z"),
        "md5" : "3c31ca011a5e50c9ca508cf1cf893dfa",
        "name" : "afdb/afdb-capeverde",
        "publisher" : "afdb",
        "received" : ISODate("2021-02-03T13:46:29.508Z"),
        "updated" : ISODate("2021-01-28T23:04:48.858Z"),
        "url" : "https://www.afdb.org/sites/default/files/iati/iaticapeverdedata.xml",
        "file-type" : "iati-file",
        "iati-version" : "2.01",
        "json-updated" : ISODate("2021-02-03T13:56:55Z"),
        "json-version" : "1.0.0"
}`

Note the SHA1 values are the same - this is what the Validator looks at to understand the file has changed - and clearly, by the result of the Datastore API, it hasn't.

And so, to conclude, we'll attend to this minor issue of the return code of 500 vs 404 in the fullness of time, but that will not remedy the actual cause of the issue, which lies with the Datastore API implementation.

Again, many thanks @andylolz for your time and valuable input.

**Comment by siemvaessen** [comment]
Sorry @alexlydiate too early for final conclusions. Other team Zimmerman team members will engage in this thread as they hold the technical finesse on Datastore codebase.

**Comment by alexlydiate** [comment]
It's not too early for our conclusion - the evidence is above, and conclusive.

That should lead Zimmerman to be able to rectify the issue.

**Comment by siemvaessen** [comment]
Ah yes, I have many anecdotal recollections as well on getting to Datastore to communicate to Validator and vice versa. Too fragile I'd argue. But not so much on topic.

Should Zimmerman come to the same conclusion as you do then we'll be on our way.

Enjoy your weekend now!

**Comment by sylvanr** [comment]
Hey guys!

What I'm able to gather from this thread is the following conclusions:

>The two files do indeed differ - the opening Activities tags are...
> And indeed, whist the Datastore holds the new version on file, its API is still reporting the same SHA1 hash as the old version.

What is this based on? If the _latest_ Cape Verde file is hashed to sha1 like @andylolz did with md5, we get the SHA1 hash that is present in your database. If we do the same for the file that is in the "internal_url" field, we get the exact same output.

```
import requests
from hashlib import md5, sha1

r = requests.get('https://www.afdb.org/sites/default/files/iati/iaticapeverdedata.xml')
print(md5(r.content).hexdigest())  # 4b4e9743feffbdee827723fd75d6101b
r = requests.get('https://www.afdb.org/sites/default/files/iati/iaticapeverdedata.xml')
print(sha1(r.content).hexdigest())  # cf6101f1c9f8b882a9875076ec05854781910453

r = requests.get('https://iati.cloud/static/datasets/46002/Activity/2.01/iaticapeverdedata.xml')
print(md5(r.content).hexdigest())  # 4b4e9743feffbdee827723fd75d6101b
r = requests.get('https://iati.cloud/static/datasets/46002/Activity/2.01/iaticapeverdedata.xml')
print(sha1(r.content).hexdigest())  # cf6101f1c9f8b882a9875076ec05854781910453
```
I just checked with Lu Min, and we have not updated our source files within the last day. So how could the MD5 in the `validator db record` you posted be different to the expected md5. Looking at the `lastseen` date, which is this morning, it should have been updated. 

I do see a [return](https://github.com/IATI/IATI-Validator-Server/blob/master/server/boot/jobs/datastore.js#L112) statement on line 112 before the md5hash is updated. Could it be that the update is executed successfully and therefore the part of the function containing the md5 hashing is not reached in the processing?

**Comment by alexlydiate** [comment]
The difference in files is the difference in the file the Validator downloaded from the Datastore as a response to finding a new SHA1 value in the DS API response, and the presently published file.

The `lastseen` date doesn't reflect a change - this is simply there as a marker as to whether the file should be removed from the Validator, it has no other purpose.

The trigger to validation is on change of the SHA1 hash.

As far as the Validator is concerned, there is no file history - each unique file, as defined by the SHA1 returned from the Datastore, is treated individually, and if the SHA1 is not present in the return from the DS API then that file is removed from the Validator.

So, it's possible that the DS API reported the SHA1 of the new version at a point it was still serving the old file - but, that's conjecture.

Yes, the program will return if it finds a record with the same SHA1 value - but if the SHA1 value is the same, the MD5 must be the same, so that's expected behaviour.

**Comment by sylvanr** [comment]
> So, it's possible that the DS API reported the SHA1 of the new version at a point it was still serving the old file - but, that's conjecture.

In this case, this sounds like the most likely (and extremely unlucky) situation due to unfortunate timing. Just discussed with Lu Min, we've identified a solution for this on our end; however, in the interest of robustness, would it be a good idea to have a regular check to ensure all of the md5 hashes are correct?

**Comment by alexlydiate** [comment]
Glad to hear you've identified the issue and the solution.

From the Validator side, we're not implementing new features in V1 - in V2 we're going to provide a properly designed public-facing API, and we're going to be getting our source files directly from publishers, via the Registry. That will allow robust integration with the Validator by the Datastore, and indeed by any other user. We'll shortly be making the draft API contract available - I believe it'll go out on Connect.

**Comment by siemvaessen** [comment]
Great stuff! We'll revert on Datastore end. Many thanks @andylolz for your time and valuable input and reiterating my issue 😅
